import React from 'react'
export const metadata = {
    title: "YourTasks",
    // description: "Generated by create next app",
  };
const page = () => {
  return (
    <div>Show Tasks</div>
  )
}

export default page