import Link from "next/link";
import React from "react";
export const metadata = {
    title: " Task Manager ",
    // description: "Generated by create next app",
  };
const CustomNavbar = () => { 
  return (
    <div>
      <nav className="bg-green-600 h-16 text-white py-2 px-36 flex justify-between items-center">
        <div className="brand">
          <h1 className="text-2xl font-semibold">
            <Link href="#!">Task Manager</Link>
          </h1>
        </div>
        <div>
          <ul className="flex space-x-5">
            <li>
              <Link href="/" className="text-white">Home</Link>
            </li>
            <li>
              <Link href="/add-task" className="text-white">Add Task</Link>
            </li>
            <li>
              <Link href="/show-task" className="text-white">Show Task</Link>
            </li>
          </ul>
        </div>
        <div>
          <ul className="flex space-x-5 mt-">
            <li>
              <Link href="/login" className="text-white">Login</Link>
            </li>
            <li>
              <Link href="/logout" className="text-white">Logout</Link>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  );
};

export default CustomNavbar;
