import React from 'react'
import AddTask from './AddTask';
export const metadata = {
  title: "AddTasks",
  // description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <AddTask/>
    </div>
  )
}

export default page